version: '3.7'

services:
    jibri:
        image: marcoadasilvaa/jibri
        restart: always
        volumes:
            - ${CONFIG}/jibri:/config
            - /dev/shm:/dev/shm
        cap_add:
            - SYS_ADMIN
            - NET_BIND_SERVICE
        devices:
            - /dev/snd:/dev/snd
        environment:
            - DOCKER_HOST_ADDRESS
            - XMPP_DOMAIN
            - XMPP_SERVER
            - XMPP_AUTH_DOMAIN
            - XMPP_INTERNAL_MUC_DOMAIN
            - XMPP_RECORDER_DOMAIN
            - JIBRI_XMPP_USER
            - JIBRI_XMPP_PASSWORD
            - JIBRI_BREWERY_MUC
            - JIBRI_RECORDER_USER
            - JIBRI_RECORDER_PASSWORD
            - JIBRI_RECORDING_DIR
            - JIBRI_FINALIZE_RECORDING_SCRIPT_PATH
            - JIBRI_DROPBOX_APIKEY
            - JIBRI_STRIP_DOMAIN_JID
            - JIBRI_LOGS_DIR
            - JIBRI_EXTERNAL_INSTANCE
            - DISPLAY=:0
            - TZ
#        networks:
#            meet.jitsi:
        healthcheck:
            test: ( (tail -n20 ${JIBRI_LOGS_DIR}/log.0.txt | grep -Eom1 'java.lang.Thread.run' && kill 1) || (curl -sfk https://${LETSENCRYPT_DOMAIN}/static/dialInInfo.html || kill 1))
            interval: 3s
            timeout: 1s
            retries: 1
            start_period: 2s

